[package]
name = "android-client"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1"
jni = "0.21"
span-core = { path = "../../crates/span-core", features = ["opus"] }
span-transport = { path = "../../crates/span-transport", default-features = false, features = ["udp"] }
tokio = { version = "1", features = ["macros", "net", "rt", "sync", "time"] }
